services:
  - type: web
    name: psychology-reviews
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mysite.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings
      - key: SECRET_KEY
        fromDatabase:
          name: psychology-reviews-db
          property: secret_key
      - key: NAVER_MAPS_CLIENT_ID
        fromDatabase:
          name: psychology-reviews-db
          property: naver_maps_client_id
      - key: NAVER_MAPS_CLIENT_SECRET
        fromDatabase:
          name: psychology-reviews-db
          property: naver_maps_client_secret
      - key: ALLOWED_HOSTS
        value: psychology-reviews.onrender.com
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: psychology-reviews-db
          property: database_url
    healthCheckPath: /health/
    autoDeploy: true 