# Generated by Django 5.0.2 on 2025-05-28 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('centers', '0003_alter_center_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '사용자 프로필', 'verbose_name_plural': '사용자 프로필 목록'},
        ),
        migrations.AddField(
            model_name='profile',
            name='managed_center',
            field=models.ForeignKey(blank=True, help_text='센터운영자인 경우 관리할 센터를 선택하세요', null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.center'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', '총관리자'), ('center_manager', '센터운영자'), ('user', '일반회원')], default='user', help_text='사용자 권한을 선택하세요', max_length=20),
        ),
    ]
