# Generated by Django 5.1.3 on 2024-12-01 14:30:00

from django.db import migrations

def update_superuser_profiles(apps, schema_editor):
    """기존 superuser들의 프로필을 admin 역할로 업데이트"""
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('accounts', 'Profile')
    
    # 모든 superuser들을 찾아서 프로필 업데이트
    for user in User.objects.filter(is_superuser=True):
        try:
            profile = Profile.objects.get(user=user)
            if profile.role != 'admin':
                profile.role = 'admin'
                profile.save()
                print(f"Updated profile for superuser: {user.username}")
        except Profile.DoesNotExist:
            # 프로필이 없는 superuser는 새로 생성
            Profile.objects.create(user=user, role='admin')
            print(f"Created admin profile for superuser: {user.username}")

def reverse_update_superuser_profiles(apps, schema_editor):
    """역마이그레이션: superuser 프로필을 user로 되돌리기"""
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('accounts', 'Profile')
    
    for user in User.objects.filter(is_superuser=True):
        try:
            profile = Profile.objects.get(user=user)
            if profile.role == 'admin':
                profile.role = 'user'
                profile.save()
        except Profile.DoesNotExist:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_profile_managed_center_and_more'),
    ]

    operations = [
        migrations.RunPython(
            update_superuser_profiles,
            reverse_update_superuser_profiles,
        ),
    ]
