# Generated by Django 5.0.2 on 2025-05-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='type',
            field=models.CharField(choices=[('counseling', 'Counseling Center'), ('clinic', 'Psychiatry Clinic')], default='counseling', help_text='상담소 유형을 선택하세요', max_length=20),
        ),
    ]
