# Generated by Django 5.0.2 on 2025-05-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_center_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='type',
            field=models.CharField(choices=[('counseling', '심리상담센터'), ('clinic', '정신건강의학과')], default='counseling', help_text='상담소 유형을 선택하세요', max_length=20),
        ),
    ]
