# Generated by Django 5.0.7 on 2024-08-11 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_center_latitude_center_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='center',
            name='operating_hours',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('specialty', models.CharField(max_length=200)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapists', to='centers.center')),
            ],
        ),
    ]
