# Generated by Django 5.0.7 on 2024-08-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_review_user_alter_review_date_alter_review_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
