# Generated by Django 5.0.7 on 2024-10-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_alter_review_date_alter_review_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='center_images/'),
        ),
    ]
