# Generated by Django 5.0.2 on 2025-05-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_restorehistory_backuphistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorehistory',
            name='media_files_count',
            field=models.IntegerField(default=0, help_text='복원된 미디어 파일 수'),
        ),
    ]
