# Generated by Django 5.0.2 on 2025-05-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0006_restorehistory_media_files_count'),
    ]

    operations = [
        # SQLite에서 Foreign Key 제약 조건을 CASCADE로 수정
        migrations.RunSQL(
            # Forward SQL - Foreign Key 제약 조건 비활성화 후 테이블 재생성
            """
            PRAGMA foreign_keys = OFF;
            
            -- CenterImage 테이블 재생성
            CREATE TABLE centers_centerimage_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                image VARCHAR(100) NOT NULL,
                created_at DATETIME NOT NULL,
                center_id BIGINT NOT NULL REFERENCES centers_center(id) ON DELETE CASCADE
            );
            
            INSERT INTO centers_centerimage_new 
            SELECT id, image, created_at, center_id FROM centers_centerimage;
            
            DROP TABLE centers_centerimage;
            ALTER TABLE centers_centerimage_new RENAME TO centers_centerimage;
            
            -- Therapist 테이블 재생성
            CREATE TABLE centers_therapist_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name VARCHAR(50) NOT NULL,
                specialty VARCHAR(100) NOT NULL,
                description TEXT NOT NULL,
                photo VARCHAR(100),
                experience INTEGER UNSIGNED NOT NULL,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL,
                center_id BIGINT NOT NULL REFERENCES centers_center(id) ON DELETE CASCADE
            );
            
            INSERT INTO centers_therapist_new 
            SELECT id, name, specialty, description, photo, experience, created_at, updated_at, center_id 
            FROM centers_therapist;
            
            DROP TABLE centers_therapist;
            ALTER TABLE centers_therapist_new RENAME TO centers_therapist;
            
            -- Review 테이블 재생성
            CREATE TABLE centers_review_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                title VARCHAR(100) NOT NULL,
                content TEXT NOT NULL,
                rating INTEGER NOT NULL,
                date DATE NOT NULL,
                url VARCHAR(200) NOT NULL,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL,
                likes INTEGER UNSIGNED NOT NULL,
                dislikes INTEGER UNSIGNED NOT NULL,
                center_id BIGINT NOT NULL REFERENCES centers_center(id) ON DELETE CASCADE,
                user_id INTEGER NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE
            );
            
            INSERT INTO centers_review_new 
            SELECT id, title, content, rating, date, url, created_at, updated_at, likes, dislikes, center_id, user_id 
            FROM centers_review;
            
            DROP TABLE centers_review;
            ALTER TABLE centers_review_new RENAME TO centers_review;
            
            -- ExternalReview 테이블 재생성
            CREATE TABLE centers_externalreview_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                title VARCHAR(255) NOT NULL,
                url VARCHAR(200) NOT NULL,
                summary VARCHAR(100) NOT NULL,
                source VARCHAR(50) NOT NULL,
                created_at DATETIME NOT NULL,
                likes INTEGER UNSIGNED NOT NULL,
                dislikes INTEGER UNSIGNED NOT NULL,
                center_id BIGINT NOT NULL REFERENCES centers_center(id) ON DELETE CASCADE
            );
            
            INSERT INTO centers_externalreview_new 
            SELECT id, title, url, summary, source, created_at, likes, dislikes, center_id 
            FROM centers_externalreview;
            
            DROP TABLE centers_externalreview;
            ALTER TABLE centers_externalreview_new RENAME TO centers_externalreview;
            
            -- ReviewComment 테이블 재생성
            CREATE TABLE centers_reviewcomment_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                content TEXT NOT NULL,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL,
                is_active BOOLEAN NOT NULL,
                author_id INTEGER NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
                review_id BIGINT NOT NULL REFERENCES centers_review(id) ON DELETE CASCADE
            );
            
            INSERT INTO centers_reviewcomment_new 
            SELECT id, content, created_at, updated_at, is_active, author_id, review_id 
            FROM centers_reviewcomment;
            
            DROP TABLE centers_reviewcomment;
            ALTER TABLE centers_reviewcomment_new RENAME TO centers_reviewcomment;
            
            PRAGMA foreign_keys = ON;
            """,
            # Reverse SQL - 되돌리기 (필요시)
            """
            -- 이 마이그레이션은 되돌릴 수 없습니다.
            -- 데이터베이스를 백업에서 복원해야 합니다.
            """
        ),
    ]
