# Generated by Django 5.2 on 2025-04-19 15:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0007_remove_center_images_centerimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={'ordering': ['-created_at'], 'verbose_name': '상담소', 'verbose_name_plural': '상담소 목록'},
        ),
        migrations.AlterModelOptions(
            name='centerimage',
            options={'ordering': ['-created_at'], 'verbose_name': '상담소 이미지', 'verbose_name_plural': '상담소 이미지 목록'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date'], 'verbose_name': '리뷰', 'verbose_name_plural': '리뷰 목록'},
        ),
        migrations.RemoveField(
            model_name='center',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='review',
            name='url',
        ),
        migrations.AddField(
            model_name='center',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일'),
        ),
        migrations.AddField(
            model_name='center',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='centerimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='center',
            name='address',
            field=models.CharField(max_length=500, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='center',
            name='contact',
            field=models.CharField(max_length=100, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='center',
            name='description',
            field=models.TextField(blank=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='center',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='center',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=200, verbose_name='상담소 이름'),
        ),
        migrations.AlterField(
            model_name='center',
            name='operating_hours',
            field=models.CharField(blank=True, max_length=200, verbose_name='운영시간'),
        ),
        migrations.AlterField(
            model_name='center',
            name='url',
            field=models.URLField(blank=True, verbose_name='웹사이트'),
        ),
        migrations.AlterField(
            model_name='centerimage',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='centers.center', verbose_name='상담소'),
        ),
        migrations.AlterField(
            model_name='centerimage',
            name='image',
            field=models.ImageField(upload_to='centers/', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='review',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='centers.center', verbose_name='상담소'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='review',
            name='summary',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
