# Generated by Django 5.0.2 on 2025-06-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0007_auto_20250530_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUploadProxy',
            fields=[
            ],
            options={
                'verbose_name': 'CSV 데이터 업로드',
                'verbose_name_plural': '📊 CSV 데이터 업로드',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('centers.center',),
        ),
    ]
