# Generated by Django 5.0.2 on 2025-06-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0008_csvuploadproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVUploadProxy',
        ),
        migrations.AddField(
            model_name='center',
            name='image_url',
            field=models.URLField(blank=True, help_text='Cloudinary에 저장된 이미지 URL', null=True),
        ),
        migrations.AddField(
            model_name='centerimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Cloudinary에 저장된 이미지 URL', null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Cloudinary에 저장된 상담사 사진 URL', null=True),
        ),
    ]
