# Generated by Django 5.2 on 2025-04-21 06:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0008_alter_center_options_alter_centerimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapist',
            options={'ordering': ['-experience'], 'verbose_name': '상담사', 'verbose_name_plural': '상담사 목록'},
        ),
        migrations.AddField(
            model_name='therapist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='therapists/', verbose_name='사진'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapists', to='centers.center', verbose_name='상담소'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='experience',
            field=models.IntegerField(verbose_name='경력(년)'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='name',
            field=models.CharField(max_length=200, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='specialty',
            field=models.CharField(max_length=200, verbose_name='전문 분야'),
        ),
    ]
