# Generated by Django 5.2 on 2025-04-22 01:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0008_alter_center_options_alter_centerimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='experience',
        ),
        migrations.AddField(
            model_name='therapist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='therapist',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='therapists/'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
