# Generated by Django 5.2 on 2025-04-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0009_remove_therapist_experience_therapist_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='경력(년)'),
        ),
    ]
