# Generated by Django 5.0.2 on 2025-06-03 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_post_board_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(help_text='예: 무료, 10,000원, 50% 할인', max_length=100, verbose_name='가격')),
                ('start_date', models.DateTimeField(verbose_name='이벤트 시작일')),
                ('end_date', models.DateTimeField(verbose_name='이벤트 종료일')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_detail', to='boards.post')),
            ],
            options={
                'verbose_name': '이벤트 상세정보',
                'verbose_name_plural': '이벤트 상세정보',
            },
        ),
    ]
